#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
    wget -O - https://get.hacs.xyz | bash -
    ln -s "${PWD}/custom_components/meteoclub" "${PWD}/config/custom_components/meteoclub"
fi

echo 'Starting Home Assistant in development mode...
    - Custom component mounted at /config/custom_components/meteoclub
    - Access UI at http://localhost:8123\n\n'

# Start Home Assistant
ass --config "${PWD}/config" --debug